# Step 1: Build Stage
FROM node:14.16.0-alpine3.13 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV REACT_APP_API_URL=http://<ip>:3001/api
RUN npm build

# Step 2: Prod Stage

FROM nginx:1.12apline
COPY --from=build-stage ./app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]