version: "3.8"

services:

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    image: vidly_web:1
    restart: unless-stopped
  api:
    build: ./backend
    image: vidly_api:1
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh
    restart: unless-stopped
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - vidly:/data/db

volumes:
  vidly:
